server:
  port: 8881

spring:
  application:
    name: hui-security
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.157.129:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 11235
        allow:
      web-stat-filter:
        enabled: true
      url: jdbc:mysql://127.0.0.1:3306/security-hui
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
#mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  global-config:
    db-config:
      table-underline: true

# mybtis sql日志
logging:
  level:
    cn.com.hui: debug